import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.BrowserCore;
import com.teamdev.jxbrowser.chromium.LoggerProvider;
import com.teamdev.jxbrowser.chromium.javafx.BrowserView;
import grafo.GraphNode;
import grafo.Node;
import heuristic.AStar;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.LinkedList;
import java.util.logging.Level;
import static javafx.application.Application.launch;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jorismar
 */
public class Gui extends javax.swing.JFrame {
    public static FindRoute search;
    public static BrowserGUI browser;
    public static String[] argsGUI;
    public static String[] orig_districts;
    public static String[] orig_roads;
    public static String[] orig_stops;

    public static String[] dest_districts;
    public static String[] dest_roads;
    public static String[] dest_stops;
    public static int origin, destiny;

    /**
     * Creates new form Gui
     */
    public Gui() {
        browser = new BrowserGUI();
        new Thread(browser).start();
        
        search = new FindRoute(browser);
        search.buildGraph();
        
        orig_districts = new String[search.getDistrictsList().size()];
        
        for(int i = 0; i < search.getDistrictsList().size(); i++)
            orig_districts[i] = search.getDistrictsList().get(i).getName();
        
        orig_roads = new String[search.getDistrictsList().getFirst().getRoads().size()];
        
        for(int i = 0; i < search.getDistrictsList().getFirst().getRoads().size(); i++)
            orig_roads[i] = search.getDistrictsList().getFirst().getRoads().get(i).getName();

        orig_stops = new String[search.getDistrictsList().getFirst().getRoads().getFirst().getStops().size()];
        
        for(int i = 0; i < search.getDistrictsList().getFirst().getRoads().size(); i++)
            orig_stops[i] = search.getDistrictsList().getFirst().getRoads().getFirst().getStops().get(i).toString();
        
        dest_districts = orig_districts;
        dest_roads = orig_roads;
        dest_stops = orig_stops;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(orig_districts));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Origem");

        jLabel2.setText("Destino");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(orig_roads));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(orig_stops));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(dest_districts));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(dest_roads));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(dest_stops));
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        browser.reload(search.find(origin, destiny));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        orig_roads = new String[search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().size()];

        for(int i = 0; i < search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().size(); i++)
            orig_roads[i] = search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(i).getName();
        
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(orig_roads));

        orig_stops = new String[search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(jComboBox7.getSelectedIndex()).getStops().size()];
        
        for(int i = 0; i < search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(0).getStops().size(); i++)
            orig_stops[i] = search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(0).getStops().get(i).toString();
        
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(orig_stops));

        origin = search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(0).getStops().get(0);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        orig_stops = new String[search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(jComboBox7.getSelectedIndex()).getStops().size()];
        
        for(int i = 0; i < search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(jComboBox7.getSelectedIndex()).getStops().size(); i++)
            orig_stops[i] = search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(jComboBox7.getSelectedIndex()).getStops().get(i).toString();
        
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(orig_stops));

        origin = search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(jComboBox7.getSelectedIndex()).getStops().get(0);
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        origin = search.getDistrictsList().get(jComboBox1.getSelectedIndex()).getRoads().get(jComboBox7.getSelectedIndex()).getStops().get(jComboBox8.getSelectedIndex());
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        dest_roads = new String[search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().size()];

        for(int i = 0; i < search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().size(); i++)
            dest_roads[i] = search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(i).getName();
        
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(dest_roads));

        dest_stops = new String[search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(0).getStops().size()];
        
        for(int i = 0; i < search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(0).getStops().size(); i++)
            dest_stops[i] = search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(0).getStops().get(i).toString();
        
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(dest_stops));

        destiny = search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(0).getStops().get(0);
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        dest_stops = new String[search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(jComboBox10.getSelectedIndex()).getStops().size()];
        
        for(int i = 0; i < search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(jComboBox10.getSelectedIndex()).getStops().size(); i++)
            dest_stops[i] = search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(jComboBox10.getSelectedIndex()).getStops().get(i).toString();
        
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(dest_stops));

        destiny = search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(jComboBox10.getSelectedIndex()).getStops().get(0);
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        destiny = search.getDistrictsList().get(jComboBox9.getSelectedIndex()).getRoads().get(jComboBox10.getSelectedIndex()).getStops().get(jComboBox11.getSelectedIndex());
    }//GEN-LAST:event_jComboBox11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        argsGUI = args;
        

/*        LinkedList<Node> route;
        AStar astar = new AStar();
        browser = new BrowserGUI(args);

        System.err.print("Building graph...");
        buildGraph();
        System.err.println("done!");

        Thread t1 = new Thread(browser);
        
        for(GraphNode nd: graph) {
            System.err.println("Node: " + nd.getRoad() + "[" + nd.getCoordinate()[0] + ", " + nd.getCoordinate()[1] + "]");
            for(Node neigh: nd.getNeighbors())
                System.err.println(" -> [" + + neigh.getCoordinate()[0] + ", " + neigh.getCoordinate()[1] + "] - " + neigh.getCostTo(nd));
        }
        
        //while (true) {
            //Scanner scan = new Scanner(System.in);
            
            String id1 = JOptionPane.showInputDialog("Origin ID: ");
            //System.err.println("Origin ID: ");
            //String id1 = scan.nextLine();

            //System.err.println("Destiny ID: ");
            String id2 = JOptionPane.showInputDialog("Destiny ID: ");//scan.nextLine();

            System.err.print("Searching route...");

            JOptionPane.showMessageDialog(null, "Searching route from " + graph.get(Integer.parseInt(id1)).getRoad() + " to " + graph.get(Integer.parseInt(id2)).getRoad());
            route = astar.findRoute(graph.get(Integer.parseInt(id1)), graph.get(Integer.parseInt(id2)));

            System.err.print("Reducing route...");
            recursiveReduction(route, route.getFirst(), route.getFirst());
            
            System.err.println("done!");

            if (route == null) {
                System.err.println("Route not found!");
                return; //continue;
            }

            routeurl = "https://www.google.com.br/maps/dir/";

            for (int i = 0; i < route.size(); i++) {
                routeurl += route.get(i).getCoordinate()[0] + "," + route.get(i).getCoordinate()[1] + "/";
            }

            //routeurl += "/data=!3e0";
            
            System.err.println("Route: " + routeurl);
            
            if(routeurl.length() > 2000){
                System.err.print("The route exceeded the limit we can to display.");
            } else {
                if(!t1.isAlive())
                    t1.start();
                else
                    browser.reload(routeurl);
            }
        //}
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
